name: Build python package

on:
  push:
    branches:
      - "main"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Build wheel
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
